CREATE TABLE `stat` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `playerId` INT NOT NULL,
  `eventId` INT NOT NULL,
  `time` DECIMAL(8,2),
  `distance` DECIMAL(8,2),
  `dateInserted` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `dateUpdated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
