CREATE TABLE `ohiotrackstats`.`team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `femaleEnrollment` INT NOT NULL,
  `maleEnrollment` INT NOT NULL,
  `dateInserted` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `dateUpdated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
